# Generated by Django 2.1.4 on 2018-12-24 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)])),
                ('workclass', models.CharField(choices=[('PR', 'Private'), ('SN', 'Self-emp-not-inc'), ('SS', 'Self-emp-inc'), ('FG', 'Federal-gov'), ('LG', 'Local-gov'), ('SG', 'State-gov'), ('WP', 'Without-pay'), ('NW', 'Never-worked')], max_length=2)),
                ('fnlwgt', models.IntegerField()),
                ('education', models.CharField(choices=[('BC', 'Bachelors'), ('SC', 'Some-College'), ('11', '11th'), ('HS', 'HS-grad'), ('PF', 'Prof-school'), ('AA', 'Assoc-acdm'), ('AV', 'Assoc-voc'), ('9T', '9th'), ('78', '7th-8th'), ('12', '12th'), ('MA', 'Masters'), ('14', '1st-4th'), ('10', '10th'), ('DR', 'Doctorate'), ('56', '5th-6th'), ('PS', 'Preschool')], max_length=2)),
                ('education_num', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('MC', 'Married-civ-spouse'), ('DV', 'Divorced'), ('NM', 'Never-married'), ('SP', 'Separated'), ('WD', 'Widowed'), ('MA', 'Married-spouse-absent'), ('MF', 'Married-AF-spouse')], max_length=2)),
                ('occupation', models.CharField(choices=[('TS', 'Tech-support'), ('CR', 'Craft-repair'), ('OS', 'Other-service'), ('SL', 'Sales'), ('EM', 'Exec-managerial'), ('PF', 'Prof-speciality'), ('HC', 'Handlers-cleaners'), ('MI', 'Machine-op-inspct'), ('AC', 'Adm-clerical'), ('FF', 'Farming-fishing'), ('TM', 'Transport-moving'), ('PH', 'Priv-house-serv'), ('PS', 'Protective-serv'), ('AF', 'Armed-Forces')], max_length=2)),
                ('relationship', models.CharField(choices=[('W', 'Wife'), ('C', 'Own-child'), ('H', 'Husband'), ('N', 'Not-in-family'), ('O', 'Other-relative'), ('U', 'Unmarried')], max_length=1)),
                ('race', models.CharField(choices=[('W', 'White'), ('I', 'Asian-Pac-Islander'), ('E', 'Amer-Indian-Eskimo'), ('O', 'Other'), ('B', 'Black')], max_length=1)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('capital_gain', models.IntegerField()),
                ('capital_loss', models.IntegerField()),
                ('hours_per_week', models.IntegerField()),
                ('native_country', models.CharField(max_length=20)),
            ],
        ),
    ]
