# Generated by Django 2.1.4 on 2018-12-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='education',
            field=models.CharField(choices=[('Bachelors', ''), ('Some-College', ''), ('11th', ''), ('HS-grad', ''), ('Prof-school', ''), ('Assoc-acdm', ''), ('Assoc-voc', ''), ('9th', ''), ('7th-8th', ''), ('12th', ''), ('Masters', ''), ('1st-4th', ''), ('10th', ''), ('Doctorate', ''), ('5th-6th', ''), ('Preschool', '')], max_length=15),
        ),
        migrations.AlterField(
            model_name='people',
            name='marital_status',
            field=models.CharField(choices=[('Married-civ-spouse', ''), ('Divorced', ''), ('Never-married', ''), ('Separated', ''), ('Widowed', ''), ('Married-spouse-absent', ''), ('Married-AF-spouse', '')], max_length=25),
        ),
        migrations.AlterField(
            model_name='people',
            name='native_country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='occupation',
            field=models.CharField(choices=[('Tech-support', ''), ('Craft-repair', ''), ('Other-service', ''), ('Sales', ''), ('Exec-managerial', ''), ('Prof-speciality', ''), ('Handlers-cleaners', ''), ('Machine-op-inspct', ''), ('Adm-clerical', ''), ('Farming-fishing', ''), ('Transport-moving', ''), ('Priv-house-serv', ''), ('Protective-serv', ''), ('Armed-Forces', '')], max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='race',
            field=models.CharField(choices=[('White', ''), ('Asian-Pac-Islander', ''), ('Amer-Indian-Eskimo', ''), ('Other', ''), ('Black', '')], max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='relationship',
            field=models.CharField(choices=[('Wife', ''), ('Own-child', ''), ('Husband', ''), ('Not-in-family', ''), ('Other-relative', ''), ('Unmarried', '')], max_length=15),
        ),
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.CharField(choices=[('Male', ''), ('Female', '')], max_length=7),
        ),
        migrations.AlterField(
            model_name='people',
            name='workclass',
            field=models.CharField(choices=[('Private', ''), ('Self-emp-not-inc', ''), ('Self-emp-inc', ''), ('Federal-gov', ''), ('Local-gov', ''), ('State-gov', ''), ('Without-pay', ''), ('Never-worked', '')], max_length=20),
        ),
    ]
