# Generated by Django 2.1.4 on 2018-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181224_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='education',
            field=models.CharField(choices=[('Bachelors', 'BC'), ('Some-College', 'SC'), ('11th', '11'), ('HS-grad', 'HS'), ('Prof-school', 'PF'), ('Assoc-acdm', 'AA'), ('Assoc-voc', 'AV'), ('9th', '9T'), ('7th-8th', '78'), ('12th', '12'), ('Masters', 'MA'), ('1st-4th', '14'), ('10th', '10'), ('Doctorate', 'DR'), ('5th-6th', '56'), ('Preschool', 'PS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='people',
            name='marital_status',
            field=models.CharField(choices=[('Married-civ-spouse', 'MC'), ('Divorced', 'DV'), ('Never-married', 'NM'), ('Separated', 'SP'), ('Widowed', 'WD'), ('Married-spouse-absent', 'MA'), ('Married-AF-spouse', 'MF')], max_length=25),
        ),
        migrations.AlterField(
            model_name='people',
            name='occupation',
            field=models.CharField(choices=[('Tech-support', 'TS'), ('Craft-repair', 'CR'), ('Other-service', 'OS'), ('Sales', 'SL'), ('Exec-managerial', 'EM'), ('Prof-speciality', 'PF'), ('Handlers-cleaners', 'HC'), ('Machine-op-inspct', 'MI'), ('Adm-clerical', 'AC'), ('Farming-fishing', 'FF'), ('Transport-moving', 'TM'), ('Priv-house-serv', 'PH'), ('Protective-serv', 'PS'), ('Armed-Forces', 'AF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='race',
            field=models.CharField(choices=[('White', 'W'), ('Asian-Pac-Islander', 'I'), ('Amer-Indian-Eskimo', 'E'), ('Other', 'O'), ('Black', 'B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='relationship',
            field=models.CharField(choices=[('Wife', 'W'), ('Own-child', 'C'), ('Husband', 'H'), ('Not-in-family', 'N'), ('Other-relative', 'O'), ('Unmarried', 'U')], max_length=15),
        ),
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=7),
        ),
        migrations.AlterField(
            model_name='people',
            name='workclass',
            field=models.CharField(choices=[('Private', 'PR'), ('Self-emp-not-inc', 'SN'), ('Self-emp-inc', 'SS'), ('Federal-gov', 'FG'), ('Local-gov', 'LG'), ('State-gov', 'SG'), ('Without-pay', 'WP'), ('Never-worked', 'NW')], max_length=20),
        ),
    ]
